CREATE TABLE CHATTING(
	ID INT IDENTITY,
	ID_REL INT,
	NOME VARCHAR(255),
	PRIMARY KEY(ID_REL, NOME)
)

CREATE TABLE CHATTING_DATA(
	ID_CHAT INT,
	NOME VARCHAR(255),
	MENSAGEM VARCHAR(255),
	DATA_ENVIO VARCHAR(20),
	TEMPO_ENVIO VARCHAR(20),
	SR_NO INT
)

CREATE SEQUENCE SEQ_CHATTING_DATA
START WITH 1
INCREMENT BY 1
MINVALUE 1
CACHE 10

CREATE VIEW NEXT_VALUE
AS
select 
case when last_used_value is null
then cast(current_value as bigint)
else cast(current_value as bigint) + 1
end as next_val
from sys.sequences where name = 'SEQ_CHATTING_DATA'

CREATE VIEW CONVERT2MESSAGE
AS
SELECT DISTINCT RU.ID_RELACIONAMENTO, RU.ID_USUARIO1, RU.ID_USUARIO2, U1.NOME AS NOME_U1, U2.NOME AS NOME_U2
FROM RELACIONAMENTO_USUARIO RU
INNER JOIN USUARIO U1
ON U1.ID_USUARIO = RU.ID_USUARIO1
INNER JOIN USUARIO U2
ON U2.ID_USUARIO = RU.ID_USUARIO2